version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: makerworks-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app:delegated
      - ./uploads:/data/uploads
    environment:
      - AVATAR_DIR=/data/uploads/avatars
      - MODEL_DIR=/data/uploads/models
      - UPLOAD_DIR=/data/uploads
      - DATABASE_URL=postgresql://jellystat:jellystat@db:5432/makerworks2
      - ASYNC_DATABASE_URL=postgresql+asyncpg://jellystat:jellystat@db:5432/makerworks2
      - JWT_SECRET_KEY=supersecretkey
      - STRIPE_SECRET_KEY=your-stripe-key
      - STRIPE_WEBHOOK_SECRET=your-webhook-secret
      - DOMAIN=http://localhost:8000
      - REDIS_URL=redis://192.168.1.170:6379/1
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15
    restart: always
    container_name: makerworks-db
    environment:
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: jellystat
      POSTGRES_DB: makerworks2
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: makerworks-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
  uploads_data: