version: '3.9'

networks:
  makerworks-net:
    external: true

volumes:
  pgdata:

services:
  backend:
    container_name: makerworks-backend
    build: .
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    networks:
      - makerworks-net
    expose:
      - "8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: makerworks-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=makerworks
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - makerworks-net

  redis:
    image: redis:7
    container_name: makerworks-redis
    networks:
      - makerworks-net

  nginx:
    image: nginx:1.28-alpine
    container_name: makerworks-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uploads:/app/uploads:ro
      - ./frontend/dist:/usr/share/nginx/html:ro  # Optional: static frontend build
    depends_on:
      - backend
    networks:
      - makerworks-net