"""add is_active to filaments

Revision ID: 23860019ec72
Revises: 8259ddb9dac6
Create Date: 2025-07-20 17:29:17.353217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23860019ec72'
down_revision: Union[str, None] = '8259ddb9dac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filaments', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filaments', 'is_active')
    # ### end Alembic commands ###
