"""Remove authentik_sub from users

Revision ID: 48b8ac7665b4
Revises: ed4feb1dceb7
Create Date: 2025-07-18 14:53:27.469517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b8ac7665b4'
down_revision: Union[str, None] = 'ed4feb1dceb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimate_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('custom_text_base_cost', sa.Float(), nullable=True),
    sa.Column('custom_text_cost_per_char', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filament_pricing',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filament_id', sa.UUID(), nullable=False),
    sa.Column('price_per_gram', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['filament_id'], ['filaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filament_pricing')
    op.drop_table('estimate_settings')
    # ### end Alembic commands ###
