"""Add model_metadata table

Revision ID: 9f1edfe2fa84
Revises: aa6a8c7a5661
Create Date: 2025-06-15 20:28:08.479511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1edfe2fa84'
down_revision: Union[str, None] = 'aa6a8c7a5661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('volume_mm3', sa.Float(), nullable=False),
    sa.Column('dimensions_mm', sa.JSON(), nullable=False),
    sa.Column('face_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_metadata')
    # ### end Alembic commands ###
