"""📐 Sync schema to models.py

Revision ID: c4fdae91b7e2
Revises: 23860019ec72
Create Date: 2025-07-20 19:04:42.488460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4fdae91b7e2'
down_revision: Union[str, None] = '23860019ec72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('estimates_user_id_fkey'), 'estimates', type_='foreignkey')
    op.create_foreign_key(None, 'estimates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('favorites_model_id_fkey'), 'favorites', type_='foreignkey')
    op.drop_constraint(op.f('favorites_user_id_fkey'), 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'models', ['model_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('filament_pricing_filament_id_fkey'), 'filament_pricing', type_='foreignkey')
    op.create_foreign_key(None, 'filament_pricing', 'filaments', ['filament_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('models_user_id_fkey'), 'models', type_='foreignkey')
    op.create_foreign_key(None, 'models', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.create_foreign_key(op.f('models_user_id_fkey'), 'models', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'filament_pricing', type_='foreignkey')
    op.create_foreign_key(op.f('filament_pricing_filament_id_fkey'), 'filament_pricing', 'filaments', ['filament_id'], ['id'])
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key(op.f('favorites_user_id_fkey'), 'favorites', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('favorites_model_id_fkey'), 'favorites', 'models', ['model_id'], ['id'])
    op.drop_constraint(None, 'estimates', type_='foreignkey')
    op.create_foreign_key(op.f('estimates_user_id_fkey'), 'estimates', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
