"""Add filament table

Revision ID: f9b3106718a8
Revises: 9f1edfe2fa84
Create Date: 2025-06-15 20:32:32.551909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b3106718a8'
down_revision: Union[str, None] = '9f1edfe2fa84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('hex', sa.String(), nullable=True),
    sa.Column('cost_per_kg', sa.Float(), nullable=False),
    sa.Column('texture', sa.String(), nullable=True),
    sa.Column('biodegradable', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filaments')
    # ### end Alembic commands ###
